### ISSUE TITLE
Feature request: Return newly created object from "add" functions

### ISSUE THREAD

**Issue by agrimpelhuber** [seatable/seatable-scripts#62]
Hope someone reads this.

Wouldn't it be possible to get a newly created row (or table ...) as the return value:

```
      const newrow = base.addRow(table,{'Name':'My Name'});
      output.text(newrow['Name']);
```

At the moment, I see no other way to mark the new rows some, and iterate over them again, ie. to link them to existing records. Tedious, to say the least.

**Comment by freeplant** [comment]
The feature is added in version 3.1.
